services:
  postgresql:
    image: postgres:alpine
    container_name: postgresql-esed
    hostname: db.esed.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .temp:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

networks:
  default:
    name: postgresql-net-esed
    driver: bridge
